name: Lint and Test
on: [pull_request]

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.14.1"
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: lint
        run: |
          pnpm install --frozen-lockfile
          pnpm lint

  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.14.1"
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Create env file
        run: |
          echo "ACALA_WS_ENDPOINT=wss://acala-rpc-1.aca-api.network" > .env

      - name: test
        run: |
          pnpm install --frozen-lockfile
          pnpm test

  build_code:
    name: build Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.14.1"
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
